### ISSUE TITLE
Aktualizacja

### ISSUE THREAD

**Issue by TomTelos** [herpoi/GraterliaOS-OpenPLi#1]
PluginBrowser linia 222, Uzupełnienie, Dzięki
    def openGOSopkg(self):
        if fileExists(resolveFilename(SCOPE_PLUGINS, "Extensions/**J00zekOPKGmgr**/GOSopkg.pyo")):
            try:
                from Plugins.Extensions.**J00zekOPKGmgr**.GOSopkg import GOSopkg
            except ImportError:
                self.session.open(MessageBox, _("**J00zekOPKGmgr***is not installed!\nPlease install it."), type = MessageBox.TYPE_INFO,timeout = 10 )
            else:
                self.session.openWithCallback(self.PluginDownloadBrowserClosed, GOSopkg, self)

**Comment by herpoi** [comment]
Zrobione.
